name: Release Chirp

on:
  push:
    branches: [ main ]
    tags:
      - "v*"    # Kører kun på tags som v1.0.0
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build via .NET
        run: dotnet build --configuration Release
        
      - name: Test via .NET
        run: |
          dotnet test test/UnitTest/Chirp.Core.Tests/Chirp.Core.Tests.csproj --configuration Release --no-restore
          dotnet test test/UnitTest/Chirp.Infrastructure.Tests/Chirp.Infrastructure.Tests.csproj --configuration Release --no-restore
          dotnet test test/UnitTest/Chirp.Web.Tests/Chirp.Web.Tests.csproj --configuration Release --no-restore
          dotnet test test/IntegrationTest/Chirp.InfrastructureTests/Chirp.InfrastructureTests.csproj --configuration Release --no-restore
          dotnet test test/IntegrationTest/Chirp.Web.IntegrationTests/Chirp.Web.IntegrationTests.csproj --configuration Release --no-restore

      - name: Publish WebApp
        run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -o publish/webapp

      - name: Upload WebApp artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: publish/webapp

      - name: Publish executables
        run: |
          # Linux (x64)
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -r linux-x64 --self-contained false -p:PublishSingleFile=true -o publish/linux-x64
          zip -j chirp-linux-x64.zip publish/linux-x64/*

      - name: Publish executables
        run: |
          # Windows (x64)
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o publish/win-x64
          zip -j chirp-win-x64.zip publish/win-x64/*
          
      - name: Publish executables
        run: |
          # macOS (x64)
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -r osx-x64 --self-contained false -p:PublishSingleFile=true -o publish/osx-x64
          zip -j chirp-osx-x64.zip publish/osx-x64/*

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chirp-linux-x64.zip
            chirp-win-x64.zip
            chirp-osx-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.Hemmelighed }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08C4F9B8641F4547A08E0DFC635181A1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C83DE56A53D46F1A16579B52272CAEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F783CAB418E406A8DF2EB057F7DBB49 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup262025chirpremotedb'
          #publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_08C4F9B8641F4547A08E0DFC635181A1 }}
          slot-name: 'Production'
          package: ./webapp